// FAIL: component embed --dummy --world into % | component embed --world %from % | component wit

package a:b;

interface i1 {
  type t = u32;
}
interface i2 {
  use i1.{t};
}
interface i3 {
  use i2.{t};
}

world into {
  export i1;
  export i2;
}

world %from {
  export x: interface {
    use i3.{t};
  }
}
